[package]
name = "shrs_line"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["MrPicklePinosaur"]
description = "readline implementation"
repository = "https://github.com/MrPicklePinosaur/sh.rs"

[dependencies]
crossterm = "0.23"
trie-rs = "0.1"